name: 'Claude Code GitHub Action'
description: 'GitHub action for Claude Code Integration in PR comments'
branding:
  icon: 'message-square'
  color: 'purple'

inputs:
  mode:
    description: 'The mode to run the action in (review, suggest, suggest-review, issue-fix, direct)'
    required: true
    default: 'review'
  pr-number:
    description: 'Pull request number (for PR-related modes)'
    required: false
  issue-number:
    description: 'Issue number (for issue-fix mode)'
    required: false
  repo-owner:
    description: 'Owner of the repository (for issue-fix mode)'
    required: false
  repo-name:
    description: 'Name of the repository (for issue-fix mode)'
    required: false
  branch-prefix:
    description: 'Prefix for the feature branch created for issue fixes'
    required: false
    default: 'fix'
  issue-label:
    description: 'Label that triggers issue fix workflows'
    required: false
    default: 'claude-fix'
  debug-mode:
    description: 'Enable full debug mode with shell tracing and Claude debug output'
    required: false
    default: 'false'
  feedback:
    description: 'The feedback text from the comment'
    required: false
  file-path:
    description: 'Path to the file being reviewed (for suggest-review mode)'
    required: false
  line-number:
    description: 'Line number in the file (for suggest-review mode)'
    required: false
  comment-id:
    description: 'GitHub comment ID to reply to (for suggest-review mode)'
    required: false
  strict-mode:
    description: 'Whether to strictly follow user requests without adding unrelated improvements'
    required: false
    default: 'true'
  anthropic-api-key:
    description: 'Anthropic API key for Claude access'
    required: true
  github-token:
    description: 'GitHub token for API access'
    required: true
  output-file:
    description: 'Path to write the output to (for direct mode)'
    required: false
    default: 'claude-code-output'

runs:
  using: 'composite'
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup GitHub CLI
      shell: bash
      run: |
        # Make sure GitHub CLI is available with token
        echo "${{ inputs.github-token }}" | gh auth login --with-token
        
    - name: Install Claude Code CLI
      shell: bash
      run: |
        # Install Claude Code CLI
        npm install -g @anthropic-ai/claude-code
        
    - name: Process Review Request
      if: inputs.mode == 'review' || inputs.mode == 'pr-comment'
      shell: bash
      run: |
        chmod +x ${{ github.action_path }}/scripts/review-mode.sh
        ${{ github.action_path }}/scripts/review-mode.sh "${{ inputs.pr-number }}" "${{ inputs.feedback }}" "${{ inputs.anthropic-api-key }}" "${{ inputs.github-token }}"
        
    - name: Process Suggested Changes
      if: inputs.mode == 'suggest'
      shell: bash
      run: |
        chmod +x ${{ github.action_path }}/scripts/suggest-mode.sh
        ${{ github.action_path }}/scripts/suggest-mode.sh "${{ inputs.pr-number }}" "${{ inputs.feedback }}" "${{ inputs.anthropic-api-key }}" "${{ inputs.github-token }}"
        
    - name: Process Direct Request
      if: inputs.mode == 'direct'
      shell: bash
      run: |
        chmod +x ${{ github.action_path }}/scripts/direct-mode.sh
        ${{ github.action_path }}/scripts/direct-mode.sh "${{ inputs.feedback }}" "${{ inputs.anthropic-api-key }}" "${{ inputs.output-file }}"
        
    - name: Process In-line Code Suggestions
      if: inputs.mode == 'suggest-review'
      shell: bash
      run: |
        chmod +x ${{ github.action_path }}/scripts/suggest-review-mode.sh
        ${{ github.action_path }}/scripts/suggest-review-mode.sh "${{ inputs.pr-number }}" "${{ inputs.feedback }}" "${{ inputs.file-path }}" "${{ inputs.line-number }}" "${{ inputs.comment-id }}" "${{ inputs.anthropic-api-key }}" "${{ inputs.github-token }}" "${{ inputs.strict-mode }}"
        
    - name: Process Issue Fix
      if: inputs.mode == 'issue-fix'
      shell: bash
      run: |
        chmod +x ${{ github.action_path }}/scripts/issue-fix-mode.sh
        ${{ github.action_path }}/scripts/issue-fix-mode.sh "${{ inputs.issue-number }}" "${{ inputs.repo-owner }}" "${{ inputs.repo-name }}" "${{ inputs.branch-prefix }}" "${{ inputs.anthropic-api-key }}" "${{ inputs.github-token }}" "${{ inputs.issue-label }}" "${{ inputs.debug-mode }}"